import type { Metadata } from "next";
import { Geist, Geist_Mono , Work_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/modules/Navbar";
import Footer from "@/modules/Footer";


const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${workSans.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
